// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfveB3VqLa1CbrB7khhfk9fYvZnWYoaU4',
    appId: '1:180028141684:web:776374914173a2760be121',
    messagingSenderId: '180028141684',
    projectId: 'myfbapp-efa1b',
    authDomain: 'myfbapp-efa1b.firebaseapp.com',
    storageBucket: 'myfbapp-efa1b.firebasestorage.app',
    measurementId: 'G-BYSNP7Q7MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8j_sxtAVd9zbnkBJMcbxajnxTlR7ric',
    appId: '1:180028141684:android:d108632f6e79dc4a0be121',
    messagingSenderId: '180028141684',
    projectId: 'myfbapp-efa1b',
    storageBucket: 'myfbapp-efa1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vYTdElUEJr1-MTx9YUTBn0rpbXYRY6U',
    appId: '1:180028141684:ios:de40eb9fb52ae9150be121',
    messagingSenderId: '180028141684',
    projectId: 'myfbapp-efa1b',
    storageBucket: 'myfbapp-efa1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vYTdElUEJr1-MTx9YUTBn0rpbXYRY6U',
    appId: '1:180028141684:ios:de40eb9fb52ae9150be121',
    messagingSenderId: '180028141684',
    projectId: 'myfbapp-efa1b',
    storageBucket: 'myfbapp-efa1b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfveB3VqLa1CbrB7khhfk9fYvZnWYoaU4',
    appId: '1:180028141684:web:856eccf2b934b43c0be121',
    messagingSenderId: '180028141684',
    projectId: 'myfbapp-efa1b',
    authDomain: 'myfbapp-efa1b.firebaseapp.com',
    storageBucket: 'myfbapp-efa1b.firebasestorage.app',
    measurementId: 'G-NYTF5SGB6H',
  );
}
